DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;
DROP TABLE ANSWERBOARD;

--글 번호 시퀀스
CREATE SEQUENCE BOARDNOSQ NOCACHE;
--그룹 번호 시퀀스(새로운 글 작성 할 때만)
CREATE SEQUENCE GROUPNOSQ NOCACHE;

CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '첫번째 글', '1번 글입니다.', '한예인', SYSDATE);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSQ;

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '두번째 글', '2번 글입니다.', '둘예인', SYSDATE);

--1번글 답글작성
--부모와 같은 GROUPNO
--부모의 GROUPSQ+1, 부모의 TITLETAB+1
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1), 
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=1)+1,
		'RE:첫번째 글', '1번 글의 답글입니다.', '한예인', SYSDATE);
		
--세번째 글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL, 1, 0, '세번째 글', '3번 글입니다.', '삼예인', SYSDATE);

--두번째 글 답글
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2), 
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		'RE:두번째 글', '2번 글의 답글입니다.', '이종민', SYSDATE);
		
--답글 작성(RE:두번쨰 글 - NO.5)
--부모와 같은 GROUPNO
--부모의 GROUPSQ+1, 부모의 TITLETAB+1
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5), 
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
		'RE:RE:두번째 글', '2번 글의 답글의 답글입니다.', '삼종민', SYSDATE);
		
--답글 작성(두번째 글 - NO.2)
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2), 
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=2)+1,
		'RE:RE:두번째 글', '2번 글의 답글의 답글입니다.', '삼종민', SYSDATE);

--답글 작성(두번째 글 - NO.2)	
UPDATE ANSWERBOARD SET GROUPSQ= GROUPSQ+1
WHERE GROUPNO=(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=2)
	AND GROUPSQ> (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=2);
		
DELETE FROM ANSWERBOARD WHERE BOARDNO=7;
		
--답변 작성(두번째 글 - NO.8)
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL,
		(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=6), 
		(SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=6)+1,
		(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=6)+1,
		'RE:RE:두번째 글', '2번 글의 답글의 답글입니다.', '삼종민', SYSDATE);

--답글 작성(두번째 글 - NO.2)	
UPDATE ANSWERBOARD SET GROUPSQ= GROUPSQ+1
WHERE GROUPNO=(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=6)
	AND GROUPSQ> (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=6);
		